import React from 'react';
import figma from '@figma/code-connect';
import { ButtonGroup } from './ButtonGroup';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

/**
 * The reason the figma connect create command only generated mappings for showEndIcon, showMidButton, and showEndButton
 * comes down to how Figma distinguishes between Component Properties and Variant Properties, and what the CLI can safely
 * assume about your code.
 * Code Connect intentionally avoids auto-mapping Variant Properties because it doesn't want to make false assumptions about
 * your codebase. For example: Does a Figma variant value of contained map to a React string prop (variant="contained"), an enum (Variant.Contained), 
 * or an entirely separate code component?
 * Is inversecolors handled via a boolean prop or a custom theme provider?
 */

figma.connect(
  ButtonGroup,
  'https://www.figma.com/design/hSgxFly4e92zns5LJXAsNB/HCLED-Components-V3--POC-?node-id=1538-116501&m=dev',
  {
    props: {
      variant: figma.enum('variant', {
        contained: 'contained',
        outlined: 'outlined',
      }),
      orientation: figma.enum('orientation', {
        horizontal: 'horizontal',
        vertical: 'vertical',
      }),
      inverseColors: figma.boolean('inverseColors', {
        true: true,
        false: false,
      }),
      showEndIcon: figma.boolean('showEndIcon', {
        true: true,
        false: false,
      }),
      showMidButton: figma.boolean('showMidButton', {
        true: true,
        false: false,
      }),
      showEndButton: figma.boolean('showEndButton', {
        true: true,
        false: false,
      }),
    },
    example: (props) => { return <ButtonGroup {...props} />; },
  },
);
